version: "3"

services:
  front:
    container_name: front
    image: nginx:alpine
    ports:
      - 8888:80
    volumes:
      - ./logs:/var/log/nginx:z
      - ./front.conf:/etc/nginx/conf.d/default.conf:z
    networks:
      - backend
  back:
    container_name: back
    image: nginx:alpine
    volumes:
      - ./www:/usr/share/nginx/html:z
      - ./back.conf:/etc/nginx/conf.d/default.conf:z
    networks:
      - backend
  php:
    container_name: php
    image: php:7.4-fpm-alpine
    volumes:
      - ./www:/usr/share/nginx/html:z
    networks:
      - backend

networks:
  backend:
    driver: bridge
